# this is for configuration as name suggests

scraper_settings:
  sleep: 1.5
  timeout: 20
  use_steamspy: true

steam_api:
  currency: "us"
  language: "en"

file_paths:
  schema: "schema.json"
  endpoints: "endpoints.json"
